spring.application.name=practiceassistant
spring.security.oauth2.resourceserver.jwt.secret-key=${JWT_SECRET_KEY}

#MYSQL Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/practiceassistant}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Allows for large file uploads over http
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
